---
deploy_user: ec2-user
deploy_key: id_rsa                   # TODO
deploy_home: "/home/{{ deploy_user }}"
deploy_bucket: stock-cs502          # TODO
repo_url: git@bitbucket.org:luffyingw/stock-cs502.git  # TODO
repo_home: "{{ deploy_home }}/aws"
